from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('register/patient/', views.create_patient, name='patient_register'),
    path('register/doctor/', views.create_doctor, name='doctor_register'),
    path('register/admin/', views.create_admin, name='admin_register'),
    path('login/', views.login_view, name='login'),
    path('patient/', views.patient_dashboard, name='patient_dashboard'),
    path('doctor/', views.doctor_dashboard, name='doctor_dashboard'),
    path('useradmin/', views.admin_dashboard, name='admin_dashboard'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('manage-facilities/', views.manage_facilities, name='manage_facilities'),
    path('manage-appointments/', views.manage_appointments, name='manage_appointments'),
    path('create-user/', views.create_user, name='create_user'),
    path('useradmin/facility/add/', views.add_facility, name='add_facility'),
    path('useradmin/edit/<int:user_id>/', views.edit_user, name='edit_user'),
    path('useradmin/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('facilities/edit/<int:id>/', views.edit_facility, name='edit_facility'),
    path('facilities/delete/<int:id>/', views.delete_facility, name='delete_facility'),
    path('logout/',views.logout_view, name='logout'),
    path('book-appointment/', views.book_appointment, name='book_appointments'),
    path('doctors/', views.doctor_list, name='doctor_list'),
    path('patient-management/', views.patient_management, name='patient_management'),
    path('appointments/<int:appointment_id>/update-status/', views.update_appointment_status, name='update_appointment_status'),
    path('prescribe/', views.prescribe, name='prescribe'),
    path('view-patient/<int:patient_id>/', views.view_patient, name='view_patient'),
    path('edit-patient/<int:patient_id>/', views.edit_patient, name='edit_patient'),
    path('delete-patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('patients/<int:patient_id>/appointments/', views.view_appointment, name='view_patient_appointments'),
    path('doctor-appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('medical-history/<int:pk>/', views.view_medical_history, name='view_medical_history'),
    path('medical_history/<int:record_id>/delete/', views.delete_medical_history, name='delete_medical_history'),
    path('doctor/create_bill/', views.create_bill, name='create_bill'),
    path('doctor/create_bill/<int:patient_id>/', views.create_bill, name='create_bill'),
    path('patient/view_bill/<int:bill_id>/', views.view_bills, name='view_bill'),
    path('patient/pay_bill/<int:bill_id>/', views.pay_bill, name='pay_bill'),
    path('user-admin/resources/', views.manage_resources, name='manage_resources'),
    path('user-admin/resources/add/', views.add_resource, name='add_resource'),
    path('user-admin/resources/edit/<int:resource_id>/', views.edit_resource, name='edit_resource'),
    path('user-admin/resources/delete/<int:resource_id>/', views.delete_resource, name='delete_resource'),
    path('prescriptions/<int:pk>/view/', views.view_prescription, name='view_prescription'),
    path('about/', views.about_us, name='about'),
    path('contactus/', views.contact_us, name='contact'),
    path('announcements/', views.announcements, name='announcements'),
    path('health-bulletin/', views.health_bulletin, name='health_bulletin'),
    path('medical-research/', views.medical_research, name='medical_research'),
    path('publications/', views.publications, name='publications'),

]
